sudo: required
services:
  - docker

language: ruby
rvm:
  - 2.5.1
gemfile: app/Gemfile

before_install:
  - docker pull hadolint/hadolint
  - gem install overcommit && gem install rubocop

script:
  - docker run --rm -i hadolint/hadolint < Dockerfile
  - overcommit --sign && overcommit --run
  - cd ./app && bundle exec rake

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never