version: '3'
services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: ${BUILD_ENV:-dev}
    image: html-converter:latest
    tty: true
    volumes:
      - "./app:/usr/src/app"
    ports:
      - 4567:${PORT:-80}
    environment:
      - APP_DIRECTORY=${APP_DIRECTORY:-/usr/src/app}