# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bundler'
gem 'down'
gem 'htmlentities'
gem 'nokogiri'
gem 'rake'
gem 'sinatra'

gem 'rerun', group: :development

gem 'rack-test', group: :test

group :test, :development do
  gem 'coveralls', require: false
  gem 'rspec'
end
